### ISSUE TITLE
Typo on import.tpl

### ISSUE THREAD

**Issue by vitor-ao** [hexonet/whmcs-ispapi-domainimport#41]
The variables {$WEB_ROOT} are written **${WEB_ROOT}** (with the dollar sign first instead of second).

**Comment by papakai** [comment]
Dear vitor-ao,

Thanks for reporting, we noticed this also. We will launch a fix for this in the next hours.
Also, `${WEB_ROOT}` doesn't work in custom smarty templates in admin area as we use it, but we found a way to populate the WHMCS default vars into a custom smarty instance.

**Comment by papakai** [comment]
fixed by v2.0.11
